name: Build GTAdhocToolchain

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Dotnet publish GTAdhocToolchain.CLI
      run: dotnet publish --configuration Release
      working-directory: ./GTAdhocToolchain.CLI

    - uses: actions/upload-artifact@v3
      with:
        name: GTAdhocToolchain
        path: |
          GTAdhocToolchain.CLI/bin/Release/net6.0/publish/*
          !GTAdhocToolchain.CLI/bin/Release/net6.0/publish/*.pdb
        if-no-files-found: error
